### ISSUE TITLE
change print command to print entire process to be run. create print-env command 

### ISSUE THREAD

**Issue by patrickhuber** [patrickhuber/cli-mgr#3]
The print command should print the entire process to be run as well as environment variables:

>/path/to/file.yml
 
```
some-password: a
some-other-var: b
```

> config.yml

```
config-sources:
- name: vcenter-yaml
  type: file
  params:
    path: /path/to/file.yml
environments:
 - name: fly
    config: cfg-file
    path: fly
    args:
    - -t
    - main
    - login
    - -u
    - atc
    - -p ((/some-password))
   env:
      TEST: one
      TEST1: ((/some-other-var))
```

currently print outputs:

> unix

```
export TEST= one
export TEST1=b
```

> windows

```
set TEST= one
set TEST1=b
```

it should print out:

> unix

```
export TEST= one
export TEST1=b

fly -t main login -u atc -p a
```

> windows

```
set TEST= one
set TEST1=b

fly -t main login -u atc -p a
```

the print-env command should take on the previous role of print.
