### ISSUE TITLE
allow configuration to be a list instead of a single value

### ISSUE THREAD

**Issue by patrickhuber** [patrickhuber/cli-mgr#6]
Currently configuration must be a single value pointing to a config-source. 

Change

```
config-sources:
- name: bosh-lab-credhub
  type: credhub
  config: bosh-lab-yaml
```

to

```
- name: bosh-lab-credhub
  type: credhub
  configurations: 
  -  bosh-lab-yaml
```

and 

```
environments:
- name: lab
  processes:  
  - name: fly
    config: bosh-lab-credhub
    path: fly
    args:
    - -t
    - main
    - login
    - -u
    - atc
    - -p ((/bosh-lab/concourse/atc_basic_auth.password))
```

to

```

environments:
- name: lab
  processes:  
  - name: fly
    configurations: 
    - bosh-lab-credhub
    path: fly
    args:
    - -t
    - main
    - login
    - -u
    - atc
    - -p ((/bosh-lab/concourse/atc_basic_auth.password))
```
